### PR TITLE
Fix defmt examples

### LINKED ISSUE #72: `.defmt` section found, but no version symbol
I get this when trying to run the examples

```
$ cargo run --example blinky --features stm32g474 -- --chip STM32G474RBTx
Compiling stm32g4xx-hal v0.0.1
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
     Running `probe-run --connect-under-reset target/thumbv7em-none-eabihf/debug/examples/blinky --chip STM32G474RBTx`
(HOST) INFO  flashing program (9 pages / 9.00 KiB)
(HOST) INFO  success!
Error: `.defmt` section found, but no version symbol - check your linker configuration
```

Adding the line `use defmt_rtt as _;` in the blinky example makes the error go away, however there is no sign of the logging output. There is no difference when replacing `info!()` with `error!()`.

---

Adding `use defmt_rtt as _;` to the example/hello (which uses `cortex_m_semihosting::hprintln` to print) gives 

```
Compiling stm32g4xx-hal v0.0.1 (stm32g4xx-hal)
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running `probe-run --connect-under-reset target/thumbv7em-none-eabihf/debug/examples/hello --chip STM32G474RBTx`
(HOST) INFO  flashing program (13 pages / 13.00 KiB)
(HOST) INFO  success!
────────────────────────────────────────────────────────────────────────────────
────────────────────────────────────────────────────────────────────────────────
stack backtrace:
   0: __c_m_sh_syscall
(HOST) WARN  call stack was corrupted; unwinding could not be completed
(HOST) ERROR error occurred during backtrace creation: debug information for address 0x80017d4 is missing. Likely fixes:
        1. compile the Rust code with `debug = 1` or higher. This is configured in the `profile.{release,bench}` sections of Cargo.toml (`profile.{dev,test}` default to `debug = 2`)
        2. use a recent version of the `cortex-m` crates (e.g. cortex-m 0.6.3 or newer). Check versions in Cargo.lock
        3. if linking to C code, compile the C code with the `-g` flag

Caused by:
    Do not have unwind info for the given address.
               the backtrace may be incomplete.
(HOST) INFO  device halted without error
```

---

To verify, I have tested https://github.com/knurling-rs/app-template which works as expected.

Am I doing something wrong or is this a bug?

stm32g4xx-hal version: 0.0.1
device: Nucleo-G474RE (STM32G474RE)

### PR DESCRIPTION
**Pull request by usbalbin**
Resolves #72 for `--features log-rtt,defmt`

Not sure how to do about rtt with non-defmt...

I have tested button, blinky, hello and panic with `--features log-rtt,defmt` and that seems to work. However I am not sure how to test log-itm etc.

### CODE REVIEW

File: examples/hello.rs [hunk 1]
```diff
@@ -5,15 +5,18 @@
...
 
+#[macro_use]
+mod utils;
+
+use utils::logger::println;
+
 #[entry]
 fn main() -> ! {
-    hprintln!("Hello, STM32G4!").unwrap();
+    let _ = println!("Hello, STM32G4!");
```
Comment (usbalbin) [inline examples/hello.rs:19]: Not sure how this should best be dealt with...

**Review by no111u3 — APPROVED** [review]
